# starship (https://starship.rs) configuration

[character]
success_symbol = "[::](bold white)"
error_symbol = "[::](dimmed white)"
# ➜

[line_break]
# disabled = true

[time]
disabled = true
use_12hr = false
format = '🕙[\[ $time \]](grey) '
time_format = "%m-%d %R"
utc_time_offset = "-5"
# time_range = "10:00:00-14:00:00"
