name: Mirror Repo
on:
  schedule:
    - cron:  '5 */1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror
      run: |
        git clone --mirror https://git.earne.link/earnestma/dotfiles.git
        cd dotfiles.git
        git remote add github "https://eeeee-bot:$TOKEN@github.com/earnestma/dotfiles.git"
        git push --mirror github
      env:
        TOKEN: ${{ secrets.TOKEN }}
